### ISSUE TITLE
Cannot Install

### ISSUE THREAD

**Issue by NigelReburn** [jugla/worldtidesinfocustom#10]
Hi, this will no longer load as an integration as neither standard or expert config can be selected - on submit the "Unknown Error Occurred" message is given.

**Comment by jugla** [comment]
Hello,
Since the last version V5.0.0 , I have added the use of matplotlib. Perhaps it is related to this.
Have you restarted HA. It has taken sometimes for me .
Please can you look in home-assistant.log if there is a keyword "Traceback" related to worldtidesinfocustom.
Thanks in advance
Philippe

**Comment by NigelReburn** [comment]
Hi Phillippe,

Nothing in the logs relating to worldtides, yes I did a couple of restarts but the error remains. I ve not used this integration before and was about to take out an admiralty subscription but a HAC integration would be much better.

Thanks in advance for helping me :)

Regards,

Nigel Reburn

**Comment by jugla** [comment]
Please, which type of HA version do you have ?
I use the core version on raspberry PI4. Just to be sure, can you look inside the following directory :  
`/srv/homeassistant/lib/python3.9/site-packages` if there are files/directory of `matplotlib` ?

**Comment by jugla** [comment]
As a workaround, have you tried within configuration.yaml
with
```yaml
##configuration.yaml example
sensor:
  - platform: worldtidesinfocustom
    name: royan_tides
    api_key: YOUR_API_KEY
    latitude: 45.61949378902948
    longitude: -1.0318721687376207
```
Perhaps, it will failed but with a clear trace in `home-assistant.log`
