### ISSUE TITLE
Can't install dependencies when running hass on a docker container.

### ISSUE THREAD

**Issue by dogmaphobic** [jugla/worldtidesinfocustom#22]
I figure this is an edge case but I might as well report it. When running Home Assistant within a Docker container, worldtidesinfocustom tries to install its dependencies in /.local. That's not how things work in a Docker container. Basically you only have access to the "config" directory.

This was installed through HACS. The error occurs during the installation of the "integration" (during the collection of dependencies - `matplotlib>=3.4.2` and `pyworldtidesinfo==3.0.1`).

![Screenshot 2023-03-09 at 2 43 29 AM](https://user-images.githubusercontent.com/749243/223946353-dc2c60d5-a4c4-4c6b-96a8-fa3d2bc007b2.jpg)
![Screenshot 2023-03-09 at 2 43 48 AM](https://user-images.githubusercontent.com/749243/223946360-77d296e4-1bd7-42f1-b1fb-36c7c21bfb76.jpg)

**Comment by jugla** [comment]
Hello,
I've checked on my side. The package is stored in the _docker_ _internal_ _directory:_ `./var/lib/docker/overlay2/XXXXXXXXXXXXXXXX/merged/usr/local/lib/python3.10/site-packages/pyworldtidesinfo`
That's consistant ==> docker manges it's own installation.

Please can you check your docker configuration, if there is something ?
Thanks in advance

**Comment by dogmaphobic** [comment]
Interesting. I'm finding it in a different place:

```
bash-5.1$ pwd
/
bash-5.1$ ls -la .var
ls: .var: No such file or directory
bash-5.1$ find / -name pyworldtidesinfo
/.local/lib/python3.10/site-packages/pyworldtidesinfo
```

**Comment by jugla** [comment]
Hello,
It is like you are connected via "root" user

**Comment by jugla** [comment]
`./var/lib/docker/` stands for `/var/lib/docker`
Sorry I just cut and paste, it was the result from `find` command

**Comment by dogmaphobic** [comment]
> It is like you are connected via "root" user

Not really. I run the docker container using its own, non privileged user. Nothing within has access to root.

```
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    restart: unless-stopped
    user: "1010:1010"
    environment:
      - TZ=America/Halifax
    volumes:
      - /home/hass/config:/config
      - /etc/localtime:/etc/localtime:ro
    privileged: true
    network_mode: host
    depends_on:
      - mariadb
      - influxdb
      - mosquitto
```
